# Generated by Django 5.2.16 on 2026-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_unified_packaging_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackaging',
            options={'ordering': ['-is_default', 'units_per_package', 'packaging_type__name']},
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='type',
            field=models.CharField(choices=[('BOX', 'Caixa'), ('BUNDLE', 'Fardo'), ('CRATE', 'Grade/engradado'), ('PACK', 'Pacote'), ('TRAY', 'Bandeja'), ('BAG', 'Saco'), ('OTHER', 'Outra')], default='OTHER', max_length=16),
        ),
    ]
