from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

OPERATIONS = [
    migrations.CreateModel(name='StockOutputItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('quantity', models.DecimalField(decimal_places=3, max_digits=14)), ('notes', models.TextField(blank=True)), ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_items', to='inventory.lot')), ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockoutput')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_items', to='inventory.product'))]),
    migrations.CreateModel(name='Supplier', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=180)), ('corporate_name', models.CharField(blank=True, max_length=180)), ('document', models.CharField(blank=True, max_length=20, null=True, unique=True)), ('state_registration', models.CharField(blank=True, max_length=30)), ('contact_name', models.CharField(blank=True, max_length=120)), ('phone', models.CharField(blank=True, max_length=30)), ('whatsapp', models.CharField(blank=True, max_length=30)), ('email', models.EmailField(blank=True, max_length=254)), ('cep', models.CharField(blank=True, max_length=10)), ('address', models.CharField(blank=True, max_length=180)), ('address_number', models.CharField(blank=True, max_length=20)), ('district', models.CharField(blank=True, max_length=100)), ('city', models.CharField(blank=True, max_length=100)), ('state', models.CharField(blank=True, max_length=2)), ('notes', models.TextField(blank=True)), ('active', models.BooleanField(default=True))], options={'ordering': ['name'], 'indexes': [models.Index(fields=['name'], name='inv_supplier_name_idx')]}),
    migrations.AddField(model_name='stockentry', name='supplier', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='inventory.supplier')),
    migrations.CreateModel(name='ProductSupplier', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('is_primary', models.BooleanField(default=False)), ('last_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='inventory.product')), ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='inventory.supplier'))]),
    migrations.AddField(model_name='product', name='supplier', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='inventory.supplier')),
    migrations.AddField(model_name='lot', name='supplier', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.supplier')),
    migrations.CreateModel(name='UserProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('full_name', models.CharField(max_length=180)), ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)), ('phone', models.CharField(blank=True, max_length=30)), ('position', models.CharField(blank=True, max_length=100)), ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERATOR', 'Operador de estoque')], default='OPERATOR', max_length=10)), ('active', models.BooleanField(default=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_profile', to=settings.AUTH_USER_MODEL))], options={'ordering': ['full_name', 'user__username']}),
    migrations.CreateModel(name='AuditLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('action', models.CharField(max_length=80)), ('entity', models.CharField(max_length=80)), ('object_id', models.CharField(blank=True, max_length=80)), ('description', models.TextField(blank=True)), ('metadata', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at'], 'indexes': [models.Index(fields=['entity', 'created_at'], name='inv_audit_entity_date_idx')]})
]
