from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

OPERATIONS = [
    migrations.AddField(model_name='lot', name='product', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product')),
    migrations.AddField(model_name='alert', name='product', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product')),
    migrations.CreateModel(name='StockAdjustment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('number', models.CharField(blank=True, max_length=32, unique=True)), ('type', models.CharField(choices=[('POSITIVE', 'Positivo'), ('NEGATIVE', 'Negativo')], max_length=10)), ('quantity', models.DecimalField(decimal_places=3, max_digits=14)), ('reason', models.CharField(max_length=200)), ('justification', models.TextField()), ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=12)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('cancelled_at', models.DateTimeField(blank=True, null=True)), ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.lot')), ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='inventory.movement')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.product')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
    migrations.CreateModel(name='StockEntry', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('number', models.CharField(blank=True, max_length=32, unique=True)), ('entry_date', models.DateTimeField(default=django.utils.timezone.now)), ('invoice_number', models.CharField(blank=True, max_length=80)), ('notes', models.TextField(blank=True)), ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=12)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('cancelled_at', models.DateTimeField(blank=True, null=True)), ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_entries', to=settings.AUTH_USER_MODEL)), ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-entry_date', '-created_at']}),
    migrations.AddField(model_name='movement', name='entry', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockentry')),
    migrations.CreateModel(name='StockEntryItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('quantity', models.DecimalField(decimal_places=3, max_digits=14)), ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)), ('lot_number', models.CharField(blank=True, max_length=80)), ('manufacturing_date', models.DateField(blank=True, null=True)), ('expiration_date', models.DateField(blank=True, null=True)), ('notes', models.TextField(blank=True)), ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry')), ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_items', to='inventory.lot')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_items', to='inventory.product'))]),
    migrations.CreateModel(name='StockOutput', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('number', models.CharField(blank=True, max_length=32, unique=True)), ('output_date', models.DateTimeField(default=django.utils.timezone.now)), ('reason', models.CharField(choices=[('COMMERCIAL', 'Retirada para comercialização'), ('TRANSFER', 'Transferência'), ('LOSS', 'Perda'), ('DAMAGE', 'Avaria'), ('EXPIRED', 'Produto vencido'), ('INTERNAL', 'Consumo interno'), ('DONATION', 'Doação'), ('ADJUSTMENT', 'Ajuste'), ('OTHER', 'Outros')], max_length=20)), ('notes', models.TextField(blank=True)), ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=12)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('cancelled_at', models.DateTimeField(blank=True, null=True)), ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_outputs', to=settings.AUTH_USER_MODEL)), ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outputs', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-output_date', '-created_at']}),
    migrations.AddField(model_name='movement', name='output', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockoutput'))
]
