import { React, useEffect, useMemo, useState, api, unwrap, fmtMoney, fmtQty, fmtDate, today, getError, Logo, Button, Modal, Toast, Field, EmptyState, Pagination, DataTable, StatusBadge, AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Boxes, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Eye, EyeOff, FileDown, FileText, Gauge, History, Layers3, LogOut, Menu, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserCog, Users, Warehouse, X, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "../shared.jsx";
import { PageHeader } from "../layout.jsx";
import { useList } from "./listing.jsx";
export function AdjustmentsPage({ notify }) {
  const list = useList("adjustments/"); const [products, setProducts] = useState([]); const [lots, setLots] = useState([]); const [form, setForm] = useState(null);
  useEffect(() => { Promise.all([api.get("products/?page_size=500&active=true"), api.get("lots/?page_size=500")]).then(([p, l]) => { setProducts(unwrap(p.data)); setLots(unwrap(l.data)); }); }, []);
  async function save(e) { e.preventDefault(); try { const r = await api.post("adjustments/", { ...form, product: Number(form.product), lot: form.lot ? Number(form.lot) : null }); await api.post(`adjustments/${r.data.id}/confirm/`); notify("Ajuste confirmado e registrado no histórico."); setForm(null); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  return <><PageHeader title="Ajustes de estoque" description="Correções autorizadas com justificativa obrigatória e histórico auditável." actions={<Button icon={Plus} onClick={() => setForm({ product: "", lot: "", type: "POSITIVE", quantity: "1", reason: "", justification: "" })}>Novo ajuste</Button>} />
    <section className="panel"><DataTable loading={list.loading} rows={list.rows} columns={[{ key: "number", label: "Número" }, { key: "created_at", label: "Data", render: (r) => fmtDate(r.created_at) }, { key: "product_name", label: "Produto" }, { key: "type", label: "Tipo", render: (r) => <StatusBadge value={r.type} label={r.type === "POSITIVE" ? "Positivo" : "Negativo"} /> }, { key: "quantity", label: "Quantidade", render: (r) => fmtQty(r.quantity) }, { key: "reason", label: "Motivo" }, { key: "status", label: "Situação", render: (r) => <StatusBadge value={r.status} /> }, { key: "user_name", label: "Responsável" }]} /></section>
    {form && <Modal title="Novo ajuste" onClose={() => setForm(null)}><form className="form-grid" onSubmit={save}><Field label="Produto" required><select value={form.product} onChange={(e) => setForm({ ...form, product: e.target.value, lot: "" })} required><option value="">Selecione</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name} — {fmtQty(p.stock)}</option>)}</select></Field><Field label="Lote"><select value={form.lot} onChange={(e) => setForm({ ...form, lot: e.target.value })}><option value="">Sem lote específico</option>{lots.filter((l) => String(l.product) === String(form.product)).map((l) => <option key={l.id} value={l.id}>{l.number} — {fmtQty(l.quantity)}</option>)}</select></Field><Field label="Tipo" required><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="POSITIVE">Positivo</option><option value="NEGATIVE">Negativo</option></select></Field><Field label="Quantidade" required><input type="number" min="1" step="1" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} required /></Field><Field label="Motivo" required><input value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} required /></Field><Field label="Justificativa" required><textarea value={form.justification} onChange={(e) => setForm({ ...form, justification: e.target.value })} required /></Field><div className="form-actions full"><Button>Confirmar ajuste</Button></div></form></Modal>}
  </>;
}
