import { React, useEffect, useMemo, useState, api, unwrap, fmtMoney, fmtQty, fmtDate, today, getError, Logo, Button, Modal, Toast, Field, EmptyState, Pagination, DataTable, StatusBadge, AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Boxes, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Eye, EyeOff, FileDown, FileText, Gauge, History, Layers3, LogOut, Menu, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserCog, Users, Warehouse, X, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "../shared.jsx";
import { PageHeader } from "../layout.jsx";
import { SearchBar, useList } from "./listing.jsx";
export function MovementsPage({ me, notify }) {
  const list = useList("movements/");
  async function reverse(row) { const reason = prompt("Motivo do estorno:", "Correção de movimentação"); if (!reason) return; try { await api.post(`movements/${row.id}/reverse/`, { reason }); notify("Movimentação estornada."); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  return <><PageHeader title="Histórico de movimentações" description="Registro imutável para auditoria, com correções feitas por estorno." />
    <div className="filters-bar"><SearchBar value={list.params.search || ""} onChange={(search) => list.setParams({ ...list.params, search, page: 1 })} /><input type="date" value={list.params.start_date || ""} onChange={(e) => list.setParams({ ...list.params, start_date: e.target.value, page: 1 })} /><input type="date" value={list.params.end_date || ""} onChange={(e) => list.setParams({ ...list.params, end_date: e.target.value, page: 1 })} /><select value={list.params.type || ""} onChange={(e) => list.setParams({ ...list.params, type: e.target.value, page: 1 })}><option value="">Todos os tipos</option><option value="ENTRY">Entrada</option><option value="OUTPUT">Saída</option><option value="ADJ_IN">Ajuste positivo</option><option value="ADJ_OUT">Ajuste negativo</option><option value="REV_IN">Estorno positivo</option><option value="REV_OUT">Estorno negativo</option></select></div>
    <section className="panel"><DataTable loading={list.loading} rows={list.rows} columns={[
      { key: "created_at", label: "Data/hora", render: (r) => fmtDate(r.created_at) }, { key: "type_display", label: "Tipo", render: (r) => <StatusBadge value={r.type} label={r.type_display} /> }, { key: "product_name", label: "Produto" }, { key: "lot_number", label: "Lote" }, { key: "previous_stock", label: "Anterior", render: (r) => fmtQty(r.previous_stock) }, { key: "quantity", label: "Movimentada", render: (r) => fmtQty(r.quantity) }, { key: "final_stock", label: "Final", render: (r) => fmtQty(r.final_stock) }, { key: "total_value", label: "Valor", render: (r) => fmtMoney(r.total_value) }, { key: "user_name", label: "Responsável" }, { key: "document", label: "Documento" }, { key: "actions", label: "Ações", render: (r) => me.permissions.is_admin && !r.reversed && !String(r.type).startsWith("REV") ? <button className="icon-btn danger" onClick={() => reverse(r)} title="Estornar"><RefreshCw size={16} /></button> : "-" },
    ]} /><Pagination page={list.params.page} count={list.count} onChange={(page) => list.setParams({ ...list.params, page })} /></section></>;
}
