import { React, useEffect, useMemo, useState, api, unwrap, fmtMoney, fmtQty, fmtDate, today, getError, Logo, Button, Modal, Toast, Field, EmptyState, Pagination, DataTable, StatusBadge, AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Boxes, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Eye, EyeOff, FileDown, FileText, Gauge, History, Layers3, LogOut, Menu, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserCog, Users, Warehouse, X, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "../shared.jsx";
import { PageHeader } from "../layout.jsx";
import { useList, SearchBar } from "./listing.jsx";
const supplierInitial = { name: "", corporate_name: "", document: "", state_registration: "", contact_name: "", phone: "", whatsapp: "", email: "", cep: "", address: "", address_number: "", district: "", city: "", state: "", notes: "", active: true };
export function SuppliersPage({ notify, me }) {
  const list = useList("suppliers/"); const [form, setForm] = useState(null);
  async function save(e) { e.preventDefault(); try { if (form.id) await api.put(`suppliers/${form.id}/`, form); else await api.post("suppliers/", form); notify("Fornecedor salvo."); setForm(null); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  return <><PageHeader title="Fornecedores" description="Dados cadastrais, contatos e histórico de recebimentos." actions={me.permissions.is_admin && <Button icon={Plus} onClick={() => setForm({ ...supplierInitial })}>Novo fornecedor</Button>} /><div className="filters-bar"><SearchBar value={list.params.search || ""} onChange={(search) => list.setParams({ ...list.params, search, page: 1 })} placeholder="Nome, documento, contato ou cidade..." /></div><section className="panel"><DataTable loading={list.loading} rows={list.rows} columns={[{ key: "name", label: "Nome fantasia", render: (r) => <span><strong>{r.name}</strong><small className="block">{r.corporate_name}</small></span> }, { key: "document", label: "CNPJ/CPF" }, { key: "contact_name", label: "Responsável" }, { key: "phone", label: "Telefone" }, { key: "city", label: "Cidade/UF", render: (r) => `${r.city || "-"}${r.state ? `/${r.state}` : ""}` }, { key: "entries_count", label: "Entradas" }, { key: "entries_value", label: "Valor recebido", render: (r) => fmtMoney(r.entries_value) }, { key: "actions", label: "Ações", render: (r) => me.permissions.is_admin ? <div className="row-actions"><button onClick={() => setForm({ ...r })}><Pencil size={16} /></button></div> : "-" }]} /><Pagination page={list.params.page} count={list.count} onChange={(page) => list.setParams({ ...list.params, page })} /></section>{form && <Modal title={form.id ? "Editar fornecedor" : "Novo fornecedor"} onClose={() => setForm(null)} size="xl"><form className="form-grid cols-3" onSubmit={save}>{[["name","Nome fantasia",true],["corporate_name","Razão social"],["document","CNPJ ou CPF"],["state_registration","Inscrição estadual"],["contact_name","Responsável"],["phone","Telefone"],["whatsapp","WhatsApp"],["email","E-mail"],["cep","CEP"],["address","Endereço"],["address_number","Número"],["district","Bairro"],["city","Cidade"],["state","Estado (UF)"]].map(([key,label,required]) => <Field key={key} label={label} required={required}><input type={key === "email" ? "email" : "text"} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required={required} /></Field>)}<Field label="Observações"><textarea value={form.notes || ""} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><Field label="Situação"><select value={String(form.active)} onChange={(e) => setForm({ ...form, active: e.target.value === "true" })}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field><div className="form-actions full"><Button type="button" variant="secondary" onClick={() => setForm(null)}>Cancelar</Button><Button>Salvar fornecedor</Button></div></form></Modal>}</>;
}
