BEGIN;
CREATE TABLE IF NOT EXISTS inventory_userprofile (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  full_name varchar(180) NOT NULL, cpf varchar(14) NULL UNIQUE, phone varchar(30) NOT NULL DEFAULT '',
  position varchar(100) NOT NULL DEFAULT '', role varchar(10) NOT NULL DEFAULT 'OPERATOR', active boolean NOT NULL DEFAULT true,
  user_id integer NOT NULL UNIQUE REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
INSERT INTO inventory_userprofile (created_at, updated_at, full_name, role, active, user_id)
SELECT now(), now(), COALESCE(NULLIF(trim(concat(first_name, ' ', last_name)), ''), username), CASE WHEN is_superuser THEN 'ADMIN' ELSE 'OPERATOR' END, is_active, id
FROM auth_user ON CONFLICT (user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS inventory_productsupplier (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  is_primary boolean NOT NULL DEFAULT false, last_cost numeric(12,2) NOT NULL DEFAULT 0,
  product_id bigint NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED,
  supplier_id bigint NOT NULL REFERENCES inventory_supplier(id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT inv_product_supplier_uniq UNIQUE(product_id, supplier_id)
);
INSERT INTO inventory_productsupplier (created_at, updated_at, is_primary, last_cost, product_id, supplier_id)
SELECT now(), now(), true, cost_price, id, supplier_id FROM inventory_product WHERE supplier_id IS NOT NULL
ON CONFLICT (product_id, supplier_id) DO NOTHING;
COMMIT;
