BEGIN;
CREATE TABLE IF NOT EXISTS inventory_stockentry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  number varchar(32) NOT NULL UNIQUE, entry_date timestamptz NOT NULL DEFAULT now(), invoice_number varchar(80) NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '', total_value numeric(14,2) NOT NULL DEFAULT 0, status varchar(12) NOT NULL DEFAULT 'DRAFT',
  confirmed_at timestamptz NULL, cancelled_at timestamptz NULL,
  supplier_id bigint NOT NULL REFERENCES inventory_supplier(id) DEFERRABLE INITIALLY DEFERRED,
  user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
  cancelled_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS inv_entry_status_date_idx ON inventory_stockentry(status, entry_date);
CREATE TABLE IF NOT EXISTS inventory_stockentryitem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  quantity numeric(14,3) NOT NULL, unit_cost numeric(12,2) NOT NULL, lot_number varchar(80) NOT NULL DEFAULT '',
  manufacturing_date date NULL, expiration_date date NULL, notes text NOT NULL DEFAULT '',
  entry_id bigint NOT NULL REFERENCES inventory_stockentry(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  product_id bigint NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED,
  lot_id bigint NULL REFERENCES inventory_lot(id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT inv_entry_item_values_valid CHECK (quantity > 0 AND unit_cost >= 0)
);

CREATE TABLE IF NOT EXISTS inventory_stockoutput (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  number varchar(32) NOT NULL UNIQUE, output_date timestamptz NOT NULL DEFAULT now(), reason varchar(20) NOT NULL,
  notes text NOT NULL DEFAULT '', status varchar(12) NOT NULL DEFAULT 'DRAFT', confirmed_at timestamptz NULL, cancelled_at timestamptz NULL,
  user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
  cancelled_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS inv_output_status_date_idx ON inventory_stockoutput(status, output_date);
CREATE TABLE IF NOT EXISTS inventory_stockoutputitem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  quantity numeric(14,3) NOT NULL, notes text NOT NULL DEFAULT '',
  output_id bigint NOT NULL REFERENCES inventory_stockoutput(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  product_id bigint NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED,
  lot_id bigint NULL REFERENCES inventory_lot(id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT inv_output_item_qty_valid CHECK (quantity > 0)
);
ALTER TABLE inventory_movement ADD COLUMN IF NOT EXISTS entry_id bigint NULL REFERENCES inventory_stockentry(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE inventory_movement ADD COLUMN IF NOT EXISTS output_id bigint NULL REFERENCES inventory_stockoutput(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS inventory_stockadjustment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  number varchar(32) NOT NULL UNIQUE, type varchar(10) NOT NULL, quantity numeric(14,3) NOT NULL,
  reason varchar(200) NOT NULL, justification text NOT NULL, status varchar(12) NOT NULL DEFAULT 'DRAFT',
  confirmed_at timestamptz NULL, cancelled_at timestamptz NULL,
  product_id bigint NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED,
  lot_id bigint NULL REFERENCES inventory_lot(id) DEFERRABLE INITIALLY DEFERRED,
  user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
  movement_id bigint NULL UNIQUE REFERENCES inventory_movement(id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT inv_adjustment_qty_valid CHECK (quantity > 0)
);
COMMIT;
