BEGIN;
ALTER TABLE inventory_inventorycount ADD COLUMN IF NOT EXISTS number varchar(32);
UPDATE inventory_inventorycount SET number = concat('INV-LEGACY-', id) WHERE number IS NULL OR number = '';
ALTER TABLE inventory_inventorycount ALTER COLUMN number SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS inventory_inventorycount_number_uniq ON inventory_inventorycount(number);
ALTER TABLE inventory_inventorycount ADD COLUMN IF NOT EXISTS started_at timestamptz;
UPDATE inventory_inventorycount SET started_at = created_at WHERE started_at IS NULL;
ALTER TABLE inventory_inventorycount ALTER COLUMN started_at SET DEFAULT now();
ALTER TABLE inventory_inventorycount ALTER COLUMN started_at SET NOT NULL;
ALTER TABLE inventory_inventorycount ADD COLUMN IF NOT EXISTS completed_at timestamptz NULL;
ALTER TABLE inventory_inventorycount ADD COLUMN IF NOT EXISTS category_id bigint NULL REFERENCES inventory_category(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE inventory_inventoryitem ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE inventory_inventoryitem ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE inventory_inventoryitem ALTER COLUMN system_quantity TYPE numeric(14,3);
ALTER TABLE inventory_inventoryitem ALTER COLUMN counted_quantity TYPE numeric(14,3);
ALTER TABLE inventory_inventoryitem ADD COLUMN IF NOT EXISTS justification text NOT NULL DEFAULT '';
ALTER TABLE inventory_inventoryitem ADD COLUMN IF NOT EXISTS adjusted boolean NOT NULL DEFAULT false;
ALTER TABLE inventory_inventoryitem ADD COLUMN IF NOT EXISTS adjustment_movement_id bigint NULL UNIQUE REFERENCES inventory_movement(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS inventory_alert (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  type varchar(30) NOT NULL, level varchar(10) NOT NULL, message varchar(255) NOT NULL, active boolean NOT NULL DEFAULT true, resolved_at timestamptz NULL,
  product_id bigint NULL REFERENCES inventory_product(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  lot_id bigint NULL REFERENCES inventory_lot(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  inventory_id bigint NULL REFERENCES inventory_inventorycount(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS inv_alert_active_type_idx ON inventory_alert(active, type);
CREATE TABLE IF NOT EXISTS inventory_notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  title varchar(160) NOT NULL, message text NOT NULL, level varchar(10) NOT NULL DEFAULT 'INFO', read boolean NOT NULL DEFAULT false, read_at timestamptz NULL,
  user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  alert_id bigint NULL REFERENCES inventory_alert(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS inventory_auditlog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, action varchar(80) NOT NULL, entity varchar(80) NOT NULL,
  object_id varchar(80) NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), user_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS inv_audit_entity_date_idx ON inventory_auditlog(entity, created_at);
CREATE TABLE IF NOT EXISTS inventory_systemsetting (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  key varchar(80) NOT NULL UNIQUE, value varchar(255) NOT NULL, description varchar(255) NOT NULL DEFAULT ''
);
INSERT INTO inventory_systemsetting(key, value, description)
VALUES ('expiration_alert_days', '30', 'Dias de antecedência para alertas de validade.'), ('low_movement_days', '30', 'Dias sem movimentação para relatório de baixa movimentação.')
ON CONFLICT (key) DO NOTHING;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'inventory_userprofile','inventory_productsupplier','inventory_stockentry','inventory_stockentryitem',
    'inventory_stockoutput','inventory_stockoutputitem','inventory_stockadjustment','inventory_alert',
    'inventory_notification','inventory_auditlog','inventory_systemsetting'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM anon, authenticated', t);
    EXECUTE format('DROP POLICY IF EXISTS deny_direct_access ON %I', t);
    EXECUTE format('CREATE POLICY deny_direct_access ON %I FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)', t);
  END LOOP;
END $$;

INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;
COMMIT;
