BEGIN;

CREATE TABLE IF NOT EXISTS public.django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_uniq
        UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL
        REFERENCES public.django_content_type(id)
        DEFERRABLE INITIALLY DEFERRED,
    codename varchar(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_codename_uniq
        UNIQUE (content_type_id, codename)
);
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_idx
    ON public.auth_permission(content_type_id);

CREATE TABLE IF NOT EXISTS public.auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.auth_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz NULL,
    is_superuser boolean NOT NULL DEFAULT false,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    date_joined timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_user_username_like_idx
    ON public.auth_user (username varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES public.auth_group(id)
        DEFERRABLE INITIALLY DEFERRED,
    permission_id integer NOT NULL REFERENCES public.auth_permission(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_group_permission_uniq
        UNIQUE (group_id, permission_id)
);
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_idx
    ON public.auth_group_permissions(group_id);
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_idx
    ON public.auth_group_permissions(permission_id);

CREATE TABLE IF NOT EXISTS public.auth_user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED,
    group_id integer NOT NULL REFERENCES public.auth_group(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_user_groups_user_group_uniq
        UNIQUE (user_id, group_id)
);
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_idx
    ON public.auth_user_groups(user_id);
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_idx
    ON public.auth_user_groups(group_id);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED,
    permission_id integer NOT NULL REFERENCES public.auth_permission(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_user_user_permissions_user_permission_uniq
        UNIQUE (user_id, permission_id)
);
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_idx
    ON public.auth_user_user_permissions(user_id);
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_idx
    ON public.auth_user_user_permissions(permission_id);

CREATE TABLE IF NOT EXISTS public.django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time timestamptz NOT NULL,
    object_id text NULL,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL CHECK (action_flag >= 0),
    change_message text NOT NULL,
    content_type_id integer NULL
        REFERENCES public.django_content_type(id)
        DEFERRABLE INITIALLY DEFERRED,
    user_id integer NOT NULL REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_idx
    ON public.django_admin_log(content_type_id);
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_idx
    ON public.django_admin_log(user_id);

CREATE TABLE IF NOT EXISTS public.django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS django_session_expire_date_idx
    ON public.django_session(expire_date);
CREATE INDEX IF NOT EXISTS django_session_session_key_like_idx
    ON public.django_session (session_key varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS public.inventory_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS inventory_category_name_like_idx
    ON public.inventory_category (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS public.inventory_supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(180) NOT NULL,
    document varchar(20) NULL UNIQUE,
    phone varchar(30) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS inventory_supplier_document_like_idx
    ON public.inventory_supplier (document varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS public.inventory_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    code varchar(50) NOT NULL UNIQUE,
    barcode varchar(80) NULL UNIQUE,
    name varchar(180) NOT NULL,
    description text NOT NULL DEFAULT '',
    brand varchar(100) NOT NULL DEFAULT '',
    unit varchar(20) NOT NULL DEFAULT 'UN',
    cost_price numeric(12,2) NOT NULL DEFAULT 0,
    sale_price numeric(12,2) NOT NULL DEFAULT 0,
    stock numeric(12,3) NOT NULL DEFAULT 0,
    minimum_stock numeric(12,3) NOT NULL DEFAULT 0,
    location varchar(100) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    category_id bigint NOT NULL
        REFERENCES public.inventory_category(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    supplier_id bigint NULL
        REFERENCES public.inventory_supplier(id)
        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_product_nonnegative_values CHECK (
        cost_price >= 0
        AND sale_price >= 0
        AND stock >= 0
        AND minimum_stock >= 0
    )
);
CREATE INDEX IF NOT EXISTS inventory_product_code_like_idx
    ON public.inventory_product (code varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS inventory_product_barcode_like_idx
    ON public.inventory_product (barcode varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS inventory_product_category_id_idx
    ON public.inventory_product(category_id);
CREATE INDEX IF NOT EXISTS inventory_product_supplier_id_idx
    ON public.inventory_product(supplier_id);
CREATE INDEX IF NOT EXISTS inventory_product_name_idx
    ON public.inventory_product(name);

CREATE TABLE IF NOT EXISTS public.inventory_lot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    number varchar(80) NOT NULL,
    quantity numeric(12,3) NOT NULL DEFAULT 0,
    expiration_date date NULL,
    product_id bigint NOT NULL REFERENCES public.inventory_product(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    supplier_id bigint NULL REFERENCES public.inventory_supplier(id)
        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_lot_product_number_uniq
        UNIQUE (product_id, number),
    CONSTRAINT inventory_lot_quantity_nonnegative CHECK (quantity >= 0)
);
CREATE INDEX IF NOT EXISTS inventory_lot_product_id_idx
    ON public.inventory_lot(product_id);
CREATE INDEX IF NOT EXISTS inventory_lot_supplier_id_idx
    ON public.inventory_lot(supplier_id);
CREATE INDEX IF NOT EXISTS inventory_lot_expiration_date_idx
    ON public.inventory_lot(expiration_date);

CREATE TABLE IF NOT EXISTS public.inventory_movement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    type varchar(5) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    previous_stock numeric(12,3) NOT NULL,
    final_stock numeric(12,3) NOT NULL,
    unit_cost numeric(12,2) NOT NULL DEFAULT 0,
    reason varchar(200) NOT NULL DEFAULT '',
    notes text NOT NULL DEFAULT '',
    reversed boolean NOT NULL DEFAULT false,
    product_id bigint NOT NULL REFERENCES public.inventory_product(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    lot_id bigint NULL REFERENCES public.inventory_lot(id)
        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    user_id integer NOT NULL REFERENCES public.auth_user(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_movement_type_valid
        CHECK (type IN ('IN','OUT','ADJ+','ADJ-','REV')),
    CONSTRAINT inventory_movement_quantities_valid CHECK (
        quantity > 0
        AND previous_stock >= 0
        AND final_stock >= 0
        AND unit_cost >= 0
    )
);
CREATE INDEX IF NOT EXISTS inventory_movement_product_id_idx
    ON public.inventory_movement(product_id);
CREATE INDEX IF NOT EXISTS inventory_movement_lot_id_idx
    ON public.inventory_movement(lot_id);
CREATE INDEX IF NOT EXISTS inventory_movement_user_id_idx
    ON public.inventory_movement(user_id);
CREATE INDEX IF NOT EXISTS inventory_movement_created_at_idx
    ON public.inventory_movement(created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_movement_type_idx
    ON public.inventory_movement(type);

CREATE TABLE IF NOT EXISTS public.inventory_inventorycount (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    status varchar(10) NOT NULL DEFAULT 'OPEN',
    notes text NOT NULL DEFAULT '',
    user_id integer NOT NULL REFERENCES public.auth_user(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_inventorycount_status_valid
        CHECK (status IN ('OPEN','DONE','CANCELLED'))
);
CREATE INDEX IF NOT EXISTS inventory_inventorycount_user_id_idx
    ON public.inventory_inventorycount(user_id);
CREATE INDEX IF NOT EXISTS inventory_inventorycount_status_idx
    ON public.inventory_inventorycount(status);

CREATE TABLE IF NOT EXISTS public.inventory_inventoryitem (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_quantity numeric(12,3) NOT NULL,
    counted_quantity numeric(12,3) NOT NULL,
    inventory_id bigint NOT NULL
        REFERENCES public.inventory_inventorycount(id)
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    product_id bigint NOT NULL REFERENCES public.inventory_product(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_inventoryitem_inventory_product_uniq
        UNIQUE (inventory_id, product_id),
    CONSTRAINT inventory_inventoryitem_quantities_nonnegative CHECK (
        system_quantity >= 0 AND counted_quantity >= 0
    )
);
CREATE INDEX IF NOT EXISTS inventory_inventoryitem_inventory_id_idx
    ON public.inventory_inventoryitem(inventory_id);
CREATE INDEX IF NOT EXISTS inventory_inventoryitem_product_id_idx
    ON public.inventory_inventoryitem(product_id);

INSERT INTO public.django_migrations (app, name, applied)
SELECT app, name, now()
FROM (VALUES
    ('contenttypes','0001_initial'),
    ('contenttypes','0002_remove_content_type_name'),
    ('auth','0001_initial'),
    ('auth','0002_alter_permission_name_max_length'),
    ('auth','0003_alter_user_email_max_length'),
    ('auth','0004_alter_user_username_opts'),
    ('auth','0005_alter_user_last_login_null'),
    ('auth','0006_require_contenttypes_0002'),
    ('auth','0007_alter_validators_add_error_messages'),
    ('auth','0008_alter_user_username_max_length'),
    ('auth','0009_alter_user_last_name_max_length'),
    ('auth','0010_alter_group_name_max_length'),
    ('auth','0011_update_proxy_permissions'),
    ('auth','0012_alter_user_first_name_max_length'),
    ('admin','0001_initial'),
    ('admin','0002_logentry_remove_auto_add'),
    ('admin','0003_logentry_add_action_flag_choices'),
    ('sessions','0001_initial'),
    ('inventory','0001_initial')
) AS migrations(app, name)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.django_migrations AS existing
    WHERE existing.app = migrations.app
      AND existing.name = migrations.name
);

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

ALTER TABLE public.inventory_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_supplier ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_lot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_inventorycount ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_inventoryitem ENABLE ROW LEVEL SECURITY;

COMMIT;
